version: '3'
services:
  rest-api:
    build: ./
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: ${DOCKER_IP} # Change here to your IP, cause idk why, but DB set on docker doesn't work with 127.0.0.1/0
      DB_PORT: 5432
      DB_USER: docker
      DB_PASSWORD: docker
      DB_NAME: docker
    links:
      - postgres
  postgres:
    image: 'postgres:latest'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
      - APP_ROOT_USER=root
      - APP_ROOT_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./src/assets/databaseInit:/docker-entrypoint-initdb.d/
