set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE USER $APP_ROOT_USER WITH PASSWORD '$APP_ROOT_PASSWORD';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE postgres TO $APP_DB_USER;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_ROOT_USER;
  GRANT ALL PRIVILEGES ON DATABASE postgres TO $APP_ROOT_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  BEGIN;
    CREATE TABLE IF NOT EXISTS user_model (
        email VARCHAR ( 200 ) UNIQUE NOT NULL,
        password VARCHAR ( 200 ) NOT NULL
    );
    INSERT INTO user_model VALUES ('jajja', 'passs');
  COMMIT;
EOSQL